### ISSUE TITLE
Migrate to @types

### ISSUE THREAD

**Issue by AyaMorisawa** [syuilo/misskey-core#33]
The type definition manager dtsm is now deprecated and will no longer be maintained.

**Comment by syuilo** [comment]
Thanks for reporting. I will migrate dtsm to @types soon ✌️

**Comment by AyaMorisawa** [comment]
https://github.com/syuilo/misskey-core/blob/9b7fc3c3097d5c8ee6b5b4aec91283d162a9c3f9/package.json#L42

**Comment by syuilo** [comment]
I fix it at 4 hours ago
https://github.com/syuilo/misskey-core/commit/d706443b86ba23c46f584ec1a9bca2dcbe9e2b8a

**Comment by AyaMorisawa** [comment]
I overlooked sorry :persevere:
